sudo: required
services:
        - docker

before_install:
        - docker build -t aa-ahmed-aa/docker-react -f Dockerfile.dev .

script:
        - docker run aa-ahmed-aa/docker-react npm run test -- --coverage